// Looks up a country flag emoji and Portuguese name from a national-team name
// (as returned by API-Football's /fixtures endpoint, which omits country code
// and national flag fields). Names are matched case-insensitively after
// trimming.
//
// Unknown names — including any non-country (club) name — get no flag and
// pass through untranslated. That naturally keeps club matches flag-free and
// keeps club names intact without an explicit "is this a country?" check.

const ISO_ALPHA2_BY_NAME: Record<string, string> = {
  // CONMEBOL
  argentina: "AR",
  bolivia: "BO",
  brazil: "BR",
  chile: "CL",
  colombia: "CO",
  ecuador: "EC",
  paraguay: "PY",
  peru: "PE",
  uruguay: "UY",
  venezuela: "VE",

  // CONCACAF
  "antigua and barbuda": "AG",
  aruba: "AW",
  bahamas: "BS",
  barbados: "BB",
  belize: "BZ",
  bermuda: "BM",
  "british virgin islands": "VG",
  canada: "CA",
  "cayman islands": "KY",
  "costa rica": "CR",
  cuba: "CU",
  curaçao: "CW",
  curacao: "CW",
  dominica: "DM",
  "dominican republic": "DO",
  "el salvador": "SV",
  grenada: "GD",
  guatemala: "GT",
  guyana: "GY",
  haiti: "HT",
  honduras: "HN",
  jamaica: "JM",
  mexico: "MX",
  montserrat: "MS",
  nicaragua: "NI",
  panama: "PA",
  "puerto rico": "PR",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  suriname: "SR",
  "trinidad and tobago": "TT",
  "turks and caicos": "TC",
  usa: "US",
  "united states": "US",
  "u.s. virgin islands": "VI",

  // UEFA (UK constituents are in SPECIAL_FLAGS below)
  albania: "AL",
  andorra: "AD",
  armenia: "AM",
  austria: "AT",
  azerbaijan: "AZ",
  belarus: "BY",
  belgium: "BE",
  "bosnia & herzegovina": "BA",
  "bosnia and herzegovina": "BA",
  bulgaria: "BG",
  croatia: "HR",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  estonia: "EE",
  "faroe islands": "FO",
  finland: "FI",
  france: "FR",
  georgia: "GE",
  germany: "DE",
  gibraltar: "GI",
  greece: "GR",
  hungary: "HU",
  iceland: "IS",
  ireland: "IE",
  "republic of ireland": "IE",
  israel: "IL",
  italy: "IT",
  kazakhstan: "KZ",
  kosovo: "XK",
  latvia: "LV",
  liechtenstein: "LI",
  lithuania: "LT",
  luxembourg: "LU",
  malta: "MT",
  moldova: "MD",
  monaco: "MC",
  montenegro: "ME",
  netherlands: "NL",
  "north macedonia": "MK",
  norway: "NO",
  poland: "PL",
  portugal: "PT",
  romania: "RO",
  russia: "RU",
  "san marino": "SM",
  serbia: "RS",
  slovakia: "SK",
  slovenia: "SI",
  spain: "ES",
  sweden: "SE",
  switzerland: "CH",
  türkiye: "TR",
  turkey: "TR",
  ukraine: "UA",

  // CAF
  algeria: "DZ",
  angola: "AO",
  benin: "BJ",
  botswana: "BW",
  "burkina faso": "BF",
  burundi: "BI",
  cameroon: "CM",
  "cape verde": "CV",
  "cape verde islands": "CV",
  "cabo verde": "CV",
  "central african republic": "CF",
  chad: "TD",
  comoros: "KM",
  congo: "CG",
  "republic of congo": "CG",
  "congo dr": "CD",
  "dr congo": "CD",
  "democratic republic of congo": "CD",
  "democratic republic of the congo": "CD",
  "côte d'ivoire": "CI",
  "cote d'ivoire": "CI",
  "ivory coast": "CI",
  djibouti: "DJ",
  egypt: "EG",
  "equatorial guinea": "GQ",
  eritrea: "ER",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  gabon: "GA",
  gambia: "GM",
  "the gambia": "GM",
  ghana: "GH",
  guinea: "GN",
  "guinea-bissau": "GW",
  kenya: "KE",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  madagascar: "MG",
  malawi: "MW",
  mali: "ML",
  mauritania: "MR",
  mauritius: "MU",
  morocco: "MA",
  mozambique: "MZ",
  namibia: "NA",
  niger: "NE",
  nigeria: "NG",
  rwanda: "RW",
  "são tomé and príncipe": "ST",
  "sao tome and principe": "ST",
  senegal: "SN",
  seychelles: "SC",
  "sierra leone": "SL",
  somalia: "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  sudan: "SD",
  tanzania: "TZ",
  togo: "TG",
  tunisia: "TN",
  uganda: "UG",
  zambia: "ZM",
  zimbabwe: "ZW",

  // AFC
  afghanistan: "AF",
  australia: "AU",
  bahrain: "BH",
  bangladesh: "BD",
  bhutan: "BT",
  brunei: "BN",
  cambodia: "KH",
  china: "CN",
  "chinese taipei": "TW",
  taiwan: "TW",
  guam: "GU",
  "hong kong": "HK",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  japan: "JP",
  jordan: "JO",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  lebanon: "LB",
  macau: "MO",
  macao: "MO",
  malaysia: "MY",
  maldives: "MV",
  mongolia: "MN",
  myanmar: "MM",
  nepal: "NP",
  "north korea": "KP",
  "korea dpr": "KP",
  oman: "OM",
  pakistan: "PK",
  palestine: "PS",
  philippines: "PH",
  qatar: "QA",
  "saudi arabia": "SA",
  singapore: "SG",
  "south korea": "KR",
  "korea republic": "KR",
  "republic of korea": "KR",
  "sri lanka": "LK",
  syria: "SY",
  tajikistan: "TJ",
  thailand: "TH",
  "timor-leste": "TL",
  turkmenistan: "TM",
  "united arab emirates": "AE",
  uae: "AE",
  uzbekistan: "UZ",
  vietnam: "VN",
  yemen: "YE",

  // OFC
  "american samoa": "AS",
  "cook islands": "CK",
  fiji: "FJ",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "papua new guinea": "PG",
  samoa: "WS",
  "solomon islands": "SB",
  tahiti: "PF",
  tonga: "TO",
  vanuatu: "VU",
};

// UK constituents need tag-sequence flag emojis (not ISO regional indicators).
const SPECIAL_FLAGS: Record<string, string> = {
  england: "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  scotland: "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  wales: "🏴\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
  "northern ireland": "🇬🇧", // No widely-supported NI subdivision flag.
};

// Portuguese (pt-BR) country names, keyed the same way as ISO_ALPHA2_BY_NAME
// and SPECIAL_FLAGS. Unknown keys fall through to the original API-Football
// name (so clubs stay intact and any new country shows in English until added).
const PT_NAME_BY_KEY: Record<string, string> = {
  // CONMEBOL
  argentina: "Argentina",
  bolivia: "Bolívia",
  brazil: "BRASIL",
  chile: "Chile",
  colombia: "Colômbia",
  ecuador: "Equador",
  paraguay: "Paraguai",
  peru: "Peru",
  uruguay: "Uruguai",
  venezuela: "Venezuela",

  // CONCACAF
  "antigua and barbuda": "Antígua e Barbuda",
  aruba: "Aruba",
  bahamas: "Bahamas",
  barbados: "Barbados",
  belize: "Belize",
  bermuda: "Bermudas",
  "british virgin islands": "Ilhas Virgens Britânicas",
  canada: "Canadá",
  "cayman islands": "Ilhas Cayman",
  "costa rica": "Costa Rica",
  cuba: "Cuba",
  curaçao: "Curaçao",
  curacao: "Curaçao",
  dominica: "Dominica",
  "dominican republic": "República Dominicana",
  "el salvador": "El Salvador",
  grenada: "Granada",
  guatemala: "Guatemala",
  guyana: "Guiana",
  haiti: "Haiti",
  honduras: "Honduras",
  jamaica: "Jamaica",
  mexico: "México",
  montserrat: "Montserrat",
  nicaragua: "Nicarágua",
  panama: "Panamá",
  "puerto rico": "Porto Rico",
  "saint kitts and nevis": "São Cristóvão e Neves",
  "saint lucia": "Santa Lúcia",
  "saint vincent and the grenadines": "São Vicente e Granadinas",
  suriname: "Suriname",
  "trinidad and tobago": "Trinidad e Tobago",
  "turks and caicos": "Turks e Caicos",
  usa: "Estados Unidos",
  "united states": "Estados Unidos",
  "u.s. virgin islands": "Ilhas Virgens Americanas",

  // UEFA
  albania: "Albânia",
  andorra: "Andorra",
  armenia: "Armênia",
  austria: "Áustria",
  azerbaijan: "Azerbaijão",
  belarus: "Bielorrússia",
  belgium: "Bélgica",
  "bosnia & herzegovina": "Bósnia e Herzegovina",
  "bosnia and herzegovina": "Bósnia e Herzegovina",
  bulgaria: "Bulgária",
  croatia: "Croácia",
  cyprus: "Chipre",
  "czech republic": "Tchéquia",
  czechia: "Tchéquia",
  denmark: "Dinamarca",
  estonia: "Estônia",
  "faroe islands": "Ilhas Faroé",
  finland: "Finlândia",
  france: "França",
  georgia: "Geórgia",
  germany: "Alemanha",
  gibraltar: "Gibraltar",
  greece: "Grécia",
  hungary: "Hungria",
  iceland: "Islândia",
  ireland: "Irlanda",
  "republic of ireland": "Irlanda",
  israel: "Israel",
  italy: "Itália",
  kazakhstan: "Cazaquistão",
  kosovo: "Kosovo",
  latvia: "Letônia",
  liechtenstein: "Liechtenstein",
  lithuania: "Lituânia",
  luxembourg: "Luxemburgo",
  malta: "Malta",
  moldova: "Moldávia",
  monaco: "Mônaco",
  montenegro: "Montenegro",
  netherlands: "Países Baixos",
  "north macedonia": "Macedônia do Norte",
  norway: "Noruega",
  poland: "Polônia",
  portugal: "Portugal",
  romania: "Romênia",
  russia: "Rússia",
  "san marino": "San Marino",
  serbia: "Sérvia",
  slovakia: "Eslováquia",
  slovenia: "Eslovênia",
  spain: "Espanha",
  sweden: "Suécia",
  switzerland: "Suíça",
  türkiye: "Turquia",
  turkey: "Turquia",
  ukraine: "Ucrânia",

  // CAF
  algeria: "Argélia",
  angola: "Angola",
  benin: "Benin",
  botswana: "Botsuana",
  "burkina faso": "Burkina Faso",
  burundi: "Burundi",
  cameroon: "Camarões",
  "cape verde": "Cabo Verde",
  "cape verde islands": "Cabo Verde",
  "cabo verde": "Cabo Verde",
  "central african republic": "República Centro-Africana",
  chad: "Chade",
  comoros: "Comores",
  congo: "Congo",
  "republic of congo": "República do Congo",
  "congo dr": "República Democrática do Congo",
  "dr congo": "República Democrática do Congo",
  "democratic republic of congo": "República Democrática do Congo",
  "democratic republic of the congo": "República Democrática do Congo",
  "côte d'ivoire": "Costa do Marfim",
  "cote d'ivoire": "Costa do Marfim",
  "ivory coast": "Costa do Marfim",
  djibouti: "Djibuti",
  egypt: "Egito",
  "equatorial guinea": "Guiné Equatorial",
  eritrea: "Eritreia",
  eswatini: "Essuatíni",
  swaziland: "Suazilândia",
  ethiopia: "Etiópia",
  gabon: "Gabão",
  gambia: "Gâmbia",
  "the gambia": "Gâmbia",
  ghana: "Gana",
  guinea: "Guiné",
  "guinea-bissau": "Guiné-Bissau",
  kenya: "Quênia",
  lesotho: "Lesoto",
  liberia: "Libéria",
  libya: "Líbia",
  madagascar: "Madagascar",
  malawi: "Malauí",
  mali: "Mali",
  mauritania: "Mauritânia",
  mauritius: "Maurício",
  morocco: "Marrocos",
  mozambique: "Moçambique",
  namibia: "Namíbia",
  niger: "Níger",
  nigeria: "Nigéria",
  rwanda: "Ruanda",
  "são tomé and príncipe": "São Tomé e Príncipe",
  "sao tome and principe": "São Tomé e Príncipe",
  senegal: "Senegal",
  seychelles: "Seicheles",
  "sierra leone": "Serra Leoa",
  somalia: "Somália",
  "south africa": "África do Sul",
  "south sudan": "Sudão do Sul",
  sudan: "Sudão",
  tanzania: "Tanzânia",
  togo: "Togo",
  tunisia: "Tunísia",
  uganda: "Uganda",
  zambia: "Zâmbia",
  zimbabwe: "Zimbábue",

  // AFC
  afghanistan: "Afeganistão",
  australia: "Austrália",
  bahrain: "Bahrein",
  bangladesh: "Bangladesh",
  bhutan: "Butão",
  brunei: "Brunei",
  cambodia: "Camboja",
  china: "China",
  "chinese taipei": "Taipé Chinesa",
  taiwan: "Taiwan",
  guam: "Guam",
  "hong kong": "Hong Kong",
  india: "Índia",
  indonesia: "Indonésia",
  iran: "Irã",
  iraq: "Iraque",
  japan: "Japão",
  jordan: "Jordânia",
  kuwait: "Kuwait",
  kyrgyzstan: "Quirguistão",
  laos: "Laos",
  lebanon: "Líbano",
  macau: "Macau",
  macao: "Macau",
  malaysia: "Malásia",
  maldives: "Maldivas",
  mongolia: "Mongólia",
  myanmar: "Mianmar",
  nepal: "Nepal",
  "north korea": "Coreia do Norte",
  "korea dpr": "Coreia do Norte",
  oman: "Omã",
  pakistan: "Paquistão",
  palestine: "Palestina",
  philippines: "Filipinas",
  qatar: "Catar",
  "saudi arabia": "Arábia Saudita",
  singapore: "Singapura",
  "south korea": "Coreia do Sul",
  "korea republic": "Coreia do Sul",
  "republic of korea": "Coreia do Sul",
  "sri lanka": "Sri Lanka",
  syria: "Síria",
  tajikistan: "Tajiquistão",
  thailand: "Tailândia",
  "timor-leste": "Timor-Leste",
  turkmenistan: "Turcomenistão",
  "united arab emirates": "Emirados Árabes Unidos",
  uae: "Emirados Árabes Unidos",
  uzbekistan: "Uzbequistão",
  vietnam: "Vietnã",
  yemen: "Iêmen",

  // OFC
  "american samoa": "Samoa Americana",
  "cook islands": "Ilhas Cook",
  fiji: "Fiji",
  "new caledonia": "Nova Caledônia",
  "new zealand": "Nova Zelândia",
  "papua new guinea": "Papua-Nova Guiné",
  samoa: "Samoa",
  "solomon islands": "Ilhas Salomão",
  tahiti: "Taiti",
  tonga: "Tonga",
  vanuatu: "Vanuatu",

  // UK constituents
  england: "Inglaterra",
  scotland: "Escócia",
  wales: "País de Gales",
  "northern ireland": "Irlanda do Norte",
};

function alpha2ToFlag(alpha2: string): string {
  const codePoints = Array.from(alpha2.toUpperCase()).map(
    (c) => 0x1f1a5 + c.charCodeAt(0)
  );
  return String.fromCodePoint(...codePoints);
}

export function flagForCountry(name: string | null | undefined): string {
  if (!name) return "";
  const key = name.trim().toLowerCase();
  if (!key) return "";
  if (SPECIAL_FLAGS[key]) return SPECIAL_FLAGS[key];
  const alpha2 = ISO_ALPHA2_BY_NAME[key];
  return alpha2 ? alpha2ToFlag(alpha2) : "";
}

export function countryNamePt(name: string | null | undefined): string {
  if (!name) return "";
  const key = name.trim().toLowerCase();
  if (!key) return name;
  return PT_NAME_BY_KEY[key] ?? name;
}
